-- Enable Row Level Security (RLS) on all tables
-- This is a CRITICAL security fix to prevent unauthorized access

-- Enable RLS on all tables
ALTER TABLE "Tenant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Role" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Campus" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OrgConfig" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Holiday" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Employee" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TeachingAssignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LeaveRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SalaryComponentDef" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EmployeeSalaryValue" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AttendanceRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PayrollRun" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PayrollItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PayrollItemLine" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EmailLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AcademicYear" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Program" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ClassSection" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Student" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Parent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StudentGuardian" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StudentEnrollment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Admission" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FeeComponentDef" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProgramFeeStructure" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Invoice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InvoiceLine" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Payment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StudentAttendance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AssessmentTemplate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AssessmentCategory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AssessmentIndicator" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StudentAssessment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StudentAssessmentScore" ENABLE ROW LEVEL SECURITY;
