// AUTO-GENERATED by scripts/generate-audit-redactor.ts. Do not edit by hand.
//
// Source: prisma/schema.prisma triple-slash @PII annotations.
// Re-run `npx tsx scripts/generate-audit-redactor.ts` after schema changes.
//
// Spec: docs/superpowers/specs/2026-05-04-erp-rebuild-foundation-design.md §5.13
// Cycle: docs/cycles/2026-05-05-p1-audit-timeline-files.md
//
// Policies:
//   - redact:      top-level field replaced with null.
//   - mask:last4:  string values → "***" + last 4 chars; values shorter
//                  than 4 chars → "***"; non-string passthrough.
//
// The redactor walks the top-level keys of the input objects only — nested
// PII would need to be flat-promoted to top-level columns to be caught.

export type PiiPolicy = "redact" | "mask:last4";
export type PiiFieldMap = Readonly<Record<string, PiiPolicy>>;
export type PiiModelMap = Readonly<Record<string, PiiFieldMap>>;

export const PII_FIELDS: PiiModelMap = Object.freeze({
  "Employee": {
    "nik": "redact",
    "phone": "mask:last4",
  },
  "Student": {
    "nik": "redact",
  },
});

type JsonObject = Record<string, unknown>;

function applyPolicy(value: unknown, policy: PiiPolicy): unknown {
  if (policy === "redact") return null;
  if (policy === "mask:last4") {
    if (typeof value !== "string") return value;
    if (value.length < 4) return "***";
    return "***" + value.slice(-4);
  }
  return value;
}

function redactShape(modelName: string, shape: unknown): unknown {
  if (shape === null || shape === undefined) return shape;
  if (typeof shape !== "object" || Array.isArray(shape)) return shape;

  const fieldMap = PII_FIELDS[modelName];
  if (!fieldMap) return shape;

  const input = shape as JsonObject;
  const output: JsonObject = { ...input };
  for (const field of Object.keys(fieldMap)) {
    if (!(field in output)) continue;
    output[field] = applyPolicy(output[field], fieldMap[field]);
  }
  return output;
}

export function redact(
  modelName: string,
  before: unknown,
  after: unknown,
): { before: unknown; after: unknown } {
  return {
    before: redactShape(modelName, before),
    after: redactShape(modelName, after),
  };
}
