// Audit redactor generator per spec §5.13.
//
// Reads prisma/schema.prisma, parses model blocks line-by-line, and emits
// lib/audit/redactor.ts containing:
//   - PII_FIELDS: a frozen per-model field map keyed by Prisma model name.
//   - redact(modelName, before, after): a helper that walks before/after
//     JSON shapes shallowly (top-level keys only), applies the per-field
//     policy, and returns the redacted shapes.
//
// Annotation grammar (triple-slash comment after the field):
//   nik    String?  @db.VarChar(16)  /// @PII redact
//   phone  String?  @db.VarChar(20)  /// @PII mask:last4
//
// Policies:
//   - redact:      top-level field replaced with null.
//   - mask:last4:  string values → "***" + last 4 chars; values shorter
//                  than 4 chars → "***"; non-string passthrough.
//
// The generator is deterministic — sorted keys, stable formatting, no
// timestamps in the header. Re-running on the same schema produces zero
// diff on the output file.
//
// Usage:  npx tsx scripts/generate-audit-redactor.ts
// Output: lib/audit/redactor.ts (overwrites)
//
// Cycle: docs/cycles/2026-05-05-p1-audit-timeline-files.md
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

type PiiPolicy = "redact" | "mask:last4";
type FieldMap = Record<string, PiiPolicy>;
type ModelMap = Record<string, FieldMap>;

const SCHEMA_PATH = resolve(__dirname, "..", "prisma", "schema.prisma");
const OUTPUT_PATH = resolve(__dirname, "..", "lib", "audit", "redactor.ts");

const PII_ANNOTATION_RE = /\/\/\/\s*@PII\s+(redact|mask:last4)\b/;
const FIELD_LINE_RE = /^\s*([A-Za-z_][A-Za-z0-9_]*)\s+/;

function parseSchema(source: string): ModelMap {
  const models: ModelMap = {};
  const lines = source.split("\n");
  let currentModel: string | null = null;
  let braceDepth = 0;

  for (const rawLine of lines) {
    const line = rawLine;
    const trimmed = line.trim();

    if (currentModel === null) {
      const modelMatch = trimmed.match(/^model\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{/);
      if (modelMatch) {
        currentModel = modelMatch[1];
        braceDepth = 1;
      }
      continue;
    }

    // Track brace nesting (Prisma model bodies don't typically nest, but be safe).
    for (const ch of trimmed) {
      if (ch === "{") braceDepth += 1;
      else if (ch === "}") braceDepth -= 1;
    }
    if (braceDepth <= 0) {
      currentModel = null;
      continue;
    }

    const piiMatch = line.match(PII_ANNOTATION_RE);
    if (!piiMatch) continue;

    const fieldMatch = line.match(FIELD_LINE_RE);
    if (!fieldMatch) continue;

    const fieldName = fieldMatch[1];
    const policy = piiMatch[1] as PiiPolicy;

    if (!models[currentModel]) models[currentModel] = {};
    models[currentModel][fieldName] = policy;
  }

  return models;
}

function sortModelMap(models: ModelMap): ModelMap {
  const sorted: ModelMap = {};
  for (const model of Object.keys(models).sort()) {
    const fields = models[model];
    const sortedFields: FieldMap = {};
    for (const field of Object.keys(fields).sort()) {
      sortedFields[field] = fields[field];
    }
    sorted[model] = sortedFields;
  }
  return sorted;
}

function emitRedactor(models: ModelMap): string {
  const sorted = sortModelMap(models);

  const fieldsLiteral = Object.entries(sorted)
    .map(([model, fields]) => {
      const fieldEntries = Object.entries(fields)
        .map(([field, policy]) => `    ${JSON.stringify(field)}: ${JSON.stringify(policy)},`)
        .join("\n");
      return `  ${JSON.stringify(model)}: {\n${fieldEntries}\n  },`;
    })
    .join("\n");

  return `// AUTO-GENERATED by scripts/generate-audit-redactor.ts. Do not edit by hand.
//
// Source: prisma/schema.prisma triple-slash @PII annotations.
// Re-run \`npx tsx scripts/generate-audit-redactor.ts\` after schema changes.
//
// Spec: docs/superpowers/specs/2026-05-04-erp-rebuild-foundation-design.md §5.13
// Cycle: docs/cycles/2026-05-05-p1-audit-timeline-files.md
//
// Policies:
//   - redact:      top-level field replaced with null.
//   - mask:last4:  string values → "***" + last 4 chars; values shorter
//                  than 4 chars → "***"; non-string passthrough.
//
// The redactor walks the top-level keys of the input objects only — nested
// PII would need to be flat-promoted to top-level columns to be caught.

export type PiiPolicy = "redact" | "mask:last4";
export type PiiFieldMap = Readonly<Record<string, PiiPolicy>>;
export type PiiModelMap = Readonly<Record<string, PiiFieldMap>>;

export const PII_FIELDS: PiiModelMap = Object.freeze({
${fieldsLiteral}
});

type JsonObject = Record<string, unknown>;

function applyPolicy(value: unknown, policy: PiiPolicy): unknown {
  if (policy === "redact") return null;
  if (policy === "mask:last4") {
    if (typeof value !== "string") return value;
    if (value.length < 4) return "***";
    return "***" + value.slice(-4);
  }
  return value;
}

function redactShape(modelName: string, shape: unknown): unknown {
  if (shape === null || shape === undefined) return shape;
  if (typeof shape !== "object" || Array.isArray(shape)) return shape;

  const fieldMap = PII_FIELDS[modelName];
  if (!fieldMap) return shape;

  const input = shape as JsonObject;
  const output: JsonObject = { ...input };
  for (const field of Object.keys(fieldMap)) {
    if (!(field in output)) continue;
    output[field] = applyPolicy(output[field], fieldMap[field]);
  }
  return output;
}

export function redact(
  modelName: string,
  before: unknown,
  after: unknown,
): { before: unknown; after: unknown } {
  return {
    before: redactShape(modelName, before),
    after: redactShape(modelName, after),
  };
}
`;
}

function main(): void {
  const schemaSource = readFileSync(SCHEMA_PATH, "utf8");
  const models = parseSchema(schemaSource);
  const output = emitRedactor(models);
  writeFileSync(OUTPUT_PATH, output, "utf8");

  const modelCount = Object.keys(models).length;
  const fieldCount = Object.values(models).reduce(
    (acc, fields) => acc + Object.keys(fields).length,
    0,
  );
  // eslint-disable-next-line no-console
  console.log(
    `generate-audit-redactor: wrote ${OUTPUT_PATH} — ${modelCount} model(s), ${fieldCount} field(s).`,
  );
}

main();
